### ISSUE TITLE
IR camera flashes a couple times and stops

### ISSUE THREAD

**Issue by madesho** [EmixamPP/linux-enable-ir-emitter#195]
**Ouput of `cat /var/local/log/linux-enable-ir-emitter/linux-enable-ir-emitter.log`**
```
[17:56:55] [debug] Executing configure command.
[17:56:55] [info] Stand in front of and close to the camera and make sure the room is well lit.
[17:56:55] [info] Ensure to not use the camera during the execution.
[17:56:55] [debug] Checking if /dev/video0 is a grayscale camera.
[17:56:57] [debug] Checking if /dev/video1 is a grayscale camera.
[17:56:57] [debug] Checking if /dev/video2 is a grayscale camera.
[17:56:58] [debug] /dev/video2 is a grayscale camera.
[17:56:58] [info] Configuring the camera /dev/video2.
[17:56:58] [debug] yaml error: bad file: /etc/linux-enable-ir-emitter/pci-0000:04:00.3-usb-0:4:1.2-video-index0.ini.
[17:56:58] [debug] No previous configuration found.
[17:56:59] [debug] Configuration for /dev/video2 saved here: /etc/linux-enable-ir-emitter/pci-0000:04:00.3-usb-0:4:1.2-video-index0.ini.
[17:57:07] [error] The emitter is already working, skipping the configuration.
[18:57:12] [debug] Executing configure command.
[18:57:12] [info] Stand in front of and close to the camera and make sure the room is well lit.
[18:57:12] [info] Ensure to not use the camera during the execution.
[18:57:12] [debug] Checking if /dev/video0 is a grayscale camera.
[18:57:14] [debug] Checking if /dev/video1 is a grayscale camera.
[18:57:14] [debug] Checking if /dev/video2 is a grayscale camera.
[18:57:16] [debug] /dev/video2 is a grayscale camera.
[18:57:16] [info] Configuring the camera /dev/video2.
[18:57:16] [debug] Previous configuration found.
[18:57:28] [debug] Instruction applied: unit: 14, selector: 6, control: 1 3 2 0 0 0 0 0 0.
[18:57:30] [debug] The instruction is not valid.
[18:57:30] [debug] Instruction applied: unit: 14, selector: 6, control: 1 3 3 0 0 0 0 0 0.
[18:57:31] [debug] The instruction is not valid.
[18:57:31] [debug] Reseting to the instruction: unit: 14, selector: 6, control: 1 3 1 0 0 0 0 0 0.
[18:57:31] [debug] Instruction applied: unit: 14, selector: 9, control: 1 0 0 0.
[18:57:32] [debug] The instruction is not valid.
[18:57:32] [debug] Reseting to the instruction: unit: 14, selector: 9, control: 1 0 0 0.
[18:57:32] [error] The configuration failed.
[18:57:32] [info] Please retry in manual mode by adding the '-m' option.
[18:57:32] [info] Do not hesitate to visit the GitHub!
[18:57:32] [info] https://github.com/EmixamPP/linux-enable-ir-emitter/blob/master/docs/README.md
[19:01:46] [debug] Executing configure command.
[19:01:46] [info] Stand in front of and close to the camera and make sure the room is well lit.
[19:01:46] [info] Ensure to not use the camera during the execution.
[19:01:46] [debug] Checking if /dev/video0 is a grayscale camera.
[19:01:47] [debug] Checking if /dev/video1 is a grayscale camera.
[19:01:47] [debug] Checking if /dev/video2 is a grayscale camera.
[19:01:49] [debug] /dev/video2 is a grayscale camera.
[19:01:49] [info] Configuring the camera /dev/video2.
[19:01:49] [debug] Previous configuration found.
[19:01:58] [debug] Instruction applied: unit: 14, selector: 6, control: 1 3 2 0 0 0 0 0 0.
[19:01:59] [debug] The instruction is not valid.
[19:01:59] [debug] Instruction applied: unit: 14, selector: 6, control: 1 3 3 0 0 0 0 0 0.
[19:02:01] [debug] The instruction is not valid.
[19:02:01] [debug] Reseting to the instruction: unit: 14, selector: 6, control: 1 3 1 0 0 0 0 0 0.
[19:02:01] [debug] Instruction applied: unit: 14, selector: 9, control: 1 0 0 0.
[19:02:02] [debug] The instruction is not valid.
[19:02:02] [debug] Reseting to the instruction: unit: 14, selector: 9, control: 1 0 0 0.
[19:02:02] [error] The configuration failed.
[19:02:02] [info] Please retry in manual mode by adding the '-m' option.
[19:02:02] [info] Do not hesitate to visit the GitHub!
[19:02:02] [info] https://github.com/EmixamPP/linux-enable-ir-emitter/blob/master/docs/README.md
[19:02:09] [debug] Executing configure command.
[19:02:09] [info] Stand in front of and close to the camera and make sure the room is well lit.
[19:02:09] [info] Ensure to not use the camera during the execution.
[19:02:09] [debug] Checking if /dev/video0 is a grayscale camera.
[19:02:09] [debug] Checking if /dev/video1 is a grayscale camera.
[19:02:09] [debug] Checking if /dev/video2 is a grayscale camera.
[19:02:10] [debug] /dev/video2 is a grayscale camera.
[19:02:10] [info] Configuring the camera /dev/video2.
[19:02:10] [debug] Previous configuration found.
[19:02:14] [debug] Instruction applied: unit: 14, selector: 6, control: 1 3 2 0 0 0 0 0 0.
[19:02:17] [debug] The instruction is not valid.
[19:02:17] [debug] Instruction applied: unit: 14, selector: 6, control: 1 3 3 0 0 0 0 0 0.
[19:02:20] [debug] The instruction is not valid.
[19:02:20] [debug] Reseting to the instruction: unit: 14, selector: 6, control: 1 3 1 0 0 0 0 0 0.
[19:02:20] [debug] Instruction applied: unit: 14, selector: 9, control: 1 0 0 0.
[19:02:23] [debug] The instruction is not valid.
[19:02:23] [debug] Reseting to the instruction: unit: 14, selector: 9, control: 1 0 0 0.
[19:02:23] [error] The configuration failed.
[19:02:23] [info] Please retry in manual mode by adding the '-m' option.
[19:02:23] [info] Do not hesitate to visit the GitHub!
[19:02:23] [info] https://github.com/EmixamPP/linux-enable-ir-emitter/blob/master/docs/README.md
[13:44:08] [debug] Executing configure command.
[13:44:08] [info] Stand in front of and close to the camera and make sure the room is well lit.
[13:44:08] [info] Ensure to not use the camera during the execution.
[13:44:08] [debug] Checking if /dev/video0 is a grayscale camera.
[13:44:10] [debug] Checking if /dev/video1 is a grayscale camera.
[13:44:10] [debug] Checking if /dev/video2 is a grayscale camera.
[13:44:12] [debug] /dev/video2 is a grayscale camera.
[13:44:12] [info] Configuring the camera /dev/video2.
[13:44:12] [debug] Previous configuration found.
[13:44:15] [error] The emitter is already working, skipping the configuration.
[02:51:54] [debug] Executing configure command.
[02:51:54] [info] Stand in front of and close to the camera and make sure the room is well lit.
[02:51:54] [info] Ensure to not use the camera during the execution.
[02:51:54] [debug] Checking if /dev/video0 is a grayscale camera.
[02:51:56] [debug] Checking if /dev/video1 is a grayscale camera.
[02:51:56] [debug] Checking if /dev/video2 is a grayscale camera.
[02:51:58] [debug] /dev/video2 is a grayscale camera.
[02:51:58] [info] Configuring the camera /dev/video2.
[02:51:58] [debug] Previous configuration found.
[02:52:01] [debug] Instruction applied: unit: 14, selector: 6, control: 1 3 2 0 0 0 0 0 0.
[02:52:02] [debug] The instruction is not valid.
[02:52:02] [debug] Instruction applied: unit: 14, selector: 6, control: 1 3 3 0 0 0 0 0 0.
[02:52:04] [debug] The instruction is not valid.
[02:52:04] [debug] Reseting to the instruction: unit: 14, selector: 6, control: 1 3 1 0 0 0 0 0 0.
[02:52:04] [debug] Instruction applied: unit: 14, selector: 9, control: 1 0 0 0.
[02:52:05] [debug] The instruction is not valid.
[02:52:05] [debug] Reseting to the instruction: unit: 14, selector: 9, control: 1 0 0 0.
[02:52:05] [error] The configuration failed.
[02:52:05] [info] Please retry in manual mode by adding the '-m' option.
[02:52:05] [info] Do not hesitate to visit the GitHub!
[02:52:05] [info] https://github.com/EmixamPP/linux-enable-ir-emitter/blob/master/docs/README.md
[02:52:37] [debug] Executing configure command.
[02:52:37] [info] Stand in front of and close to the camera and make sure the room is well lit.
[02:52:37] [info] Ensure to not use the camera during the execution.
[02:52:37] [debug] Checking if /dev/video0 is a grayscale camera.
[02:52:37] [debug] Checking if /dev/video1 is a grayscale camera.
[02:52:37] [debug] Checking if /dev/video2 is a grayscale camera.
[02:52:38] [debug] /dev/video2 is a grayscale camera.
[02:52:38] [info] Configuring the camera /dev/video2.
[02:52:38] [debug] Previous configuration found.
[02:52:41] [debug] Instruction applied: unit: 14, selector: 6, control: 1 3 2 0 0 0 0 0 0.
[02:52:43] [debug] The instruction is not valid.
[02:52:43] [debug] Instruction applied: unit: 14, selector: 6, control: 1 3 3 0 0 0 0 0 0.
[02:52:44] [debug] The instruction is not valid.
[02:52:44] [debug] Reseting to the instruction: unit: 14, selector: 6, control: 1 3 1 0 0 0 0 0 0.
[02:52:44] [debug] Instruction applied: unit: 14, selector: 9, control: 1 0 0 0.
[02:52:46] [debug] The instruction is not valid.
[02:52:46] [debug] Reseting to the instruction: unit: 14, selector: 9, control: 1 0 0 0.
[02:52:46] [error] The configuration failed.
[02:52:46] [info] Please retry in manual mode by adding the '-m' option.
[02:52:46] [info] Do not hesitate to visit the GitHub!
[02:52:46] [info] https://github.com/EmixamPP/linux-enable-ir-emitter/blob/master/docs/README.md
[03:02:49] [debug] Executing configure command.
[03:02:49] [info] Stand in front of and close to the camera and make sure the room is well lit.
[03:02:49] [info] Ensure to not use the camera during the execution.
[03:02:49] [debug] Checking if /dev/video0 is a grayscale camera.
[03:02:50] [debug] Checking if /dev/video1 is a grayscale camera.
[03:02:50] [debug] Checking if /dev/video2 is a grayscale camera.
[03:02:52] [debug] /dev/video2 is a grayscale camera.
[03:02:52] [info] Configuring the camera /dev/video2.
[03:02:52] [debug] Previous configuration found.
[03:02:57] [debug] Instruction applied: unit: 14, selector: 6, control: 1 3 2 0 0 0 0 0 0.
[03:02:59] [debug] The instruction is not valid.
[03:02:59] [debug] Instruction applied: unit: 14, selector: 6, control: 1 3 3 0 0 0 0 0 0.
[03:03:00] [debug] The instruction is not valid.
[03:03:00] [debug] Reseting to the instruction: unit: 14, selector: 6, control: 1 3 1 0 0 0 0 0 0.
[03:03:00] [debug] Instruction applied: unit: 14, selector: 9, control: 1 0 0 0.
[03:03:02] [debug] The instruction is not valid.
[03:03:02] [debug] Reseting to the instruction: unit: 14, selector: 9, control: 1 0 0 0.
[03:03:02] [error] The configuration failed.
[03:03:02] [info] Please retry in manual mode by adding the '-m' option.
[03:03:02] [info] Do not hesitate to visit the GitHub!
[03:03:02] [info] https://github.com/EmixamPP/linux-enable-ir-emitter/blob/master/docs/README.md
[03:16:43] [debug] Executing configure command.
[03:16:43] [info] Stand in front of and close to the camera and make sure the room is well lit.
[03:16:43] [info] Ensure to not use the camera during the execution.
[03:16:43] [debug] Checking if /dev/video0 is a grayscale camera.
[03:16:45] [debug] Checking if /dev/video1 is a grayscale camera.
[03:16:45] [debug] Checking if /dev/video2 is a grayscale camera.
[03:16:47] [debug] /dev/video2 is a grayscale camera.
[03:16:47] [info] Configuring the camera /dev/video2.
[03:16:47] [debug] Previous configuration found.
[03:16:52] [debug] Instruction applied: unit: 14, selector: 6, control: 1 3 2 0 0 0 0 0 0.
[03:16:54] [debug] The instruction is not valid.
[03:16:54] [debug] Instruction applied: unit: 14, selector: 6, control: 1 3 3 0 0 0 0 0 0.
[03:16:55] [debug] The instruction is not valid.
[03:16:55] [debug] Reseting to the instruction: unit: 14, selector: 6, control: 1 3 1 0 0 0 0 0 0.
[03:16:55] [debug] Instruction applied: unit: 14, selector: 9, control: 1 0 0 0.
[03:16:57] [debug] The instruction is not valid.
[03:16:57] [debug] Reseting to the instruction: unit: 14, selector: 9, control: 1 0 0 0.
[03:16:57] [error] The configuration failed.
[03:16:57] [info] Please retry in manual mode by adding the '-m' option.
[03:16:57] [info] Do not hesitate to visit the GitHub!
[03:16:57] [info] https://github.com/EmixamPP/linux-enable-ir-emitter/blob/master/docs/README.md
[03:17:01] [debug] Executing configure command.
[03:17:01] [info] Stand in front of and close to the camera and make sure the room is well lit.
[03:17:01] [info] Ensure to not use the camera during the execution.
[03:17:01] [debug] Checking if /dev/video0 is a grayscale camera.
[03:17:02] [debug] Checking if /dev/video1 is a grayscale camera.
[03:17:02] [debug] Checking if /dev/video2 is a grayscale camera.
[03:17:02] [debug] /dev/video2 is a grayscale camera.
[03:17:02] [info] Configuring the camera /dev/video2.
[03:17:02] [debug] Previous configuration found.
[03:17:04] [debug] Instruction applied: unit: 14, selector: 6, control: 1 3 2 0 0 0 0 0 0.
[03:17:06] [debug] The instruction is not valid.
[03:17:06] [debug] Instruction applied: unit: 14, selector: 6, control: 1 3 3 0 0 0 0 0 0.
[03:17:07] [debug] The instruction is not valid.
[03:17:07] [debug] Reseting to the instruction: unit: 14, selector: 6, control: 1 3 1 0 0 0 0 0 0.
[03:17:07] [debug] Instruction applied: unit: 14, selector: 9, control: 1 0 0 0.
[03:17:09] [debug] The instruction is not valid.
[03:17:09] [debug] Reseting to the instruction: unit: 14, selector: 9, control: 1 0 0 0.
[03:17:09] [error] The configuration failed.
[03:17:09] [info] Please retry in manual mode by adding the '-m' option.
[03:17:09] [info] Do not hesitate to visit the GitHub!
[03:17:09] [info] https://github.com/EmixamPP/linux-enable-ir-emitter/blob/master/docs/README.md
[03:17:32] [debug] Executing configure command.
[03:17:32] [info] Stand in front of and close to the camera and make sure the room is well lit.
[03:17:32] [info] Ensure to not use the camera during the execution.
[03:17:32] [debug] Checking if /dev/video0 is a grayscale camera.
[03:17:33] [debug] Checking if /dev/video1 is a grayscale camera.
[03:17:33] [debug] Checking if /dev/video2 is a grayscale camera.
[03:17:33] [debug] /dev/video2 is a grayscale camera.
[03:17:33] [info] Configuring the camera /dev/video2.
[03:17:33] [debug] Previous configuration found.
[03:17:36] [debug] Instruction applied: unit: 14, selector: 6, control: 1 3 2 0 0 0 0 0 0.
[03:17:37] [debug] The instruction is not valid.
[03:17:37] [debug] Instruction applied: unit: 14, selector: 6, control: 1 3 3 0 0 0 0 0 0.
[03:17:39] [debug] The instruction is not valid.
[03:17:39] [debug] Reseting to the instruction: unit: 14, selector: 6, control: 1 3 1 0 0 0 0 0 0.
[03:17:39] [debug] Instruction applied: unit: 14, selector: 9, control: 1 0 0 0.
[03:17:40] [debug] The instruction is not valid.
[03:17:40] [debug] Reseting to the instruction: unit: 14, selector: 9, control: 1 0 0 0.
[03:17:40] [error] The configuration failed.
[03:17:40] [info] Please retry in manual mode by adding the '-m' option.
[03:17:40] [info] Do not hesitate to visit the GitHub!
[03:17:40] [info] https://github.com/EmixamPP/linux-enable-ir-emitter/blob/master/docs/README.md
[03:29:42] [debug] Executing configure command.
[03:29:42] [info] Stand in front of and close to the camera and make sure the room is well lit.
[03:29:42] [info] Ensure to not use the camera during the execution.
[03:29:42] [debug] Checking if /dev/video0 is a grayscale camera.
[03:29:43] [debug] Checking if /dev/video1 is a grayscale camera.
[03:29:43] [debug] Checking if /dev/video2 is a grayscale camera.
[03:29:45] [debug] /dev/video2 is a grayscale camera.
[03:29:45] [info] Configuring the camera /dev/video2.
[03:29:45] [debug] yaml error: bad file: /etc/linux-enable-ir-emitter/pci-0000:04:00.3-usb-0:4:1.2-video-index0.ini.
[03:29:45] [debug] No previous configuration found.
[03:29:45] [debug] Configuration for /dev/video2 saved here: /etc/linux-enable-ir-emitter/pci-0000:04:00.3-usb-0:4:1.2-video-index0.ini.
[03:29:48] [debug] Instruction applied: unit: 14, selector: 6, control: 1 3 2 0 0 0 0 0 0.
[03:29:49] [debug] The instruction is not valid.
[03:29:49] [debug] Instruction applied: unit: 14, selector: 6, control: 1 3 3 0 0 0 0 0 0.
[03:29:51] [debug] The instruction is not valid.
[03:29:51] [debug] Reseting to the instruction: unit: 14, selector: 6, control: 1 3 1 0 0 0 0 0 0.
[03:29:51] [debug] Instruction applied: unit: 14, selector: 9, control: 1 0 0 0.
[03:29:52] [debug] The instruction is not valid.
[03:29:52] [debug] Reseting to the instruction: unit: 14, selector: 9, control: 1 0 0 0.
[03:29:52] [error] The configuration failed.
[03:29:52] [info] Please retry in manual mode by adding the '-m' option.
[03:29:52] [info] Do not hesitate to visit the GitHub!
[03:29:52] [info] https://github.com/EmixamPP/linux-enable-ir-emitter/blob/master/docs/README.md
[03:29:57] [debug] Executing configure command.
[03:29:57] [info] Stand in front of and close to the camera and make sure the room is well lit.
[03:29:57] [info] Ensure to not use the camera during the execution.
[03:29:57] [debug] Checking if /dev/video0 is a grayscale camera.
[03:29:58] [debug] Checking if /dev/video1 is a grayscale camera.
[03:29:58] [debug] Checking if /dev/video2 is a grayscale camera.
[03:29:58] [debug] /dev/video2 is a grayscale camera.
[03:29:58] [info] Configuring the camera /dev/video2.
[03:29:58] [debug] Previous configuration found.
[03:30:01] [debug] Instruction applied: unit: 14, selector: 6, control: 1 3 2 0 0 0 0 0 0.
[03:30:02] [debug] The instruction is not valid.
[03:30:02] [debug] Instruction applied: unit: 14, selector: 6, control: 1 3 3 0 0 0 0 0 0.
[03:30:04] [debug] The instruction is not valid.
[03:30:04] [debug] Reseting to the instruction: unit: 14, selector: 6, control: 1 3 1 0 0 0 0 0 0.
[03:30:04] [debug] Instruction applied: unit: 14, selector: 9, control: 1 0 0 0.
[03:30:05] [debug] The instruction is not valid.
[03:30:05] [debug] Reseting to the instruction: unit: 14, selector: 9, control: 1 0 0 0.
[03:30:05] [error] The configuration failed.
[03:30:05] [info] Please retry in manual mode by adding the '-m' option.
[03:30:05] [info] Do not hesitate to visit the GitHub!
[03:30:05] [info] https://github.com/EmixamPP/linux-enable-ir-emitter/blob/master/docs/README.md
[03:58:18] [debug] Executing configure command.
[03:58:18] [info] Stand in front of and close to the camera and make sure the room is well lit.
[03:58:18] [info] Ensure to not use the camera during the execution.
[03:58:18] [debug] Checking if /dev/video0 is a grayscale camera.
[03:58:19] [debug] Checking if /dev/video1 is a grayscale camera.
[03:58:19] [debug] Checking if /dev/video2 is a grayscale camera.
[03:58:21] [debug] /dev/video2 is a grayscale camera.
[03:58:21] [info] Configuring the camera /dev/video2.
[03:58:21] [debug] Previous configuration found.
[03:58:29] [debug] Instruction applied: unit: 14, selector: 6, control: 1 3 2 0 0 0 0 0 0.
[03:58:30] [debug] The instruction is not valid.
[03:58:30] [debug] Instruction applied: unit: 14, selector: 6, control: 1 3 3 0 0 0 0 0 0.
[03:58:31] [debug] The instruction is not valid.
[03:58:31] [debug] Reseting to the instruction: unit: 14, selector: 6, control: 1 3 1 0 0 0 0 0 0.
[03:58:31] [debug] Instruction applied: unit: 14, selector: 9, control: 1 0 0 0.
[03:58:33] [debug] The instruction is not valid.
[03:58:33] [debug] Reseting to the instruction: unit: 14, selector: 9, control: 1 0 0 0.
[03:58:33] [error] The configuration failed.
[03:58:33] [info] Please retry in manual mode by adding the '-m' option.
[03:58:33] [info] Do not hesitate to visit the GitHub!
[03:58:33] [info] https://github.com/EmixamPP/linux-enable-ir-emitter/blob/master/docs/README.md
[03:58:37] [debug] Executing configure command.
[03:58:37] [info] Stand in front of and close to the camera and make sure the room is well lit.
[03:58:37] [info] Ensure to not use the camera during the execution.
[03:58:37] [debug] Checking if /dev/video0 is a grayscale camera.
[03:58:38] [debug] Checking if /dev/video1 is a grayscale camera.
[03:58:38] [debug] Checking if /dev/video2 is a grayscale camera.
[03:58:38] [debug] /dev/video2 is a grayscale camera.
[03:58:38] [info] Configuring the camera /dev/video2.
[03:58:38] [debug] Previous configuration found.
[03:58:41] [debug] Instruction applied: unit: 14, selector: 6, control: 1 3 2 0 0 0 0 0 0.
[03:58:42] [debug] The instruction is not valid.
[03:58:42] [debug] Instruction applied: unit: 14, selector: 6, control: 1 3 3 0 0 0 0 0 0.
[03:58:44] [debug] The instruction is not valid.
[03:58:44] [debug] Reseting to the instruction: unit: 14, selector: 6, control: 1 3 1 0 0 0 0 0 0.
[03:58:44] [debug] Instruction applied: unit: 14, selector: 9, control: 1 0 0 0.
[03:58:46] [debug] The instruction is not valid.
[03:58:46] [debug] Reseting to the instruction: unit: 14, selector: 9, control: 1 0 0 0.
[03:58:46] [error] The configuration failed.
[03:58:46] [info] Please retry in manual mode by adding the '-m' option.
[03:58:46] [info] Do not hesitate to visit the GitHub!
[03:58:46] [info] https://github.com/EmixamPP/linux-enable-ir-emitter/blob/master/docs/README.md
```

**Output of `sudo linux-enable-ir-emitter tweak`**
```
Tweaking the camera /dev/video2
Caution, you could break the camera.

0) unit: 14, selector: 6, control: 1 3 1 0 0 0 0 0 0
1) unit: 14, selector: 9, control: 1 0 0 0
2) exit
```

**Output of `v4l2-ctl --list-devices`**
```
HP Wide Vision 5MP Camera: HP W (usb-0000:04:00.3-4):
	/dev/video0
	/dev/video1
	/dev/video2
	/dev/video3
	/dev/media0
	/dev/media1
```

**Ouput of `for dev in /dev/video*; do echo $dev && v4l2-ctl -d $dev --list-formats-ext; done`**
```
/dev/video0
ioctl: VIDIOC_ENUM_FMT
	Type: Video Capture

	[0]: 'MJPG' (Motion-JPEG, compressed)
		Size: Discrete 2592x1944
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 1280x720
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 640x360
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 640x480
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 640x640
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 1280x960
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 1920x1080
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 2560x1440
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 2592x1728
			Interval: Discrete 0.033s (30.000 fps)
	[1]: 'YUYV' (YUYV 4:2:2)
		Size: Discrete 640x480
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 640x360
			Interval: Discrete 0.033s (30.000 fps)
/dev/video1
ioctl: VIDIOC_ENUM_FMT
	Type: Video Capture

/dev/video2
ioctl: VIDIOC_ENUM_FMT
	Type: Video Capture

	[0]: 'GREY' (8-bit Greyscale)
		Size: Discrete 640x480
			Interval: Discrete 0.067s (15.000 fps)
/dev/video3
ioctl: VIDIOC_ENUM_FMT
	Type: Video Capture
```

**Output of `ls -l /dev/v4l/by-path`**
```
totale 0
lrwxrwxrwx. 1 root root 12 28 set 03.29 pci-0000:04:00.3-usb-0:4:1.0-video-index0 -> ../../video0
lrwxrwxrwx. 1 root root 12 28 set 03.29 pci-0000:04:00.3-usb-0:4:1.0-video-index1 -> ../../video1
lrwxrwxrwx. 1 root root 12 28 set 03.29 pci-0000:04:00.3-usb-0:4:1.2-video-index0 -> ../../video2
lrwxrwxrwx. 1 root root 12 28 set 03.29 pci-0000:04:00.3-usb-0:4:1.2-video-index1 -> ../../video3
lrwxrwxrwx. 1 root root 12 28 set 03.29 pci-0000:04:00.3-usbv2-0:4:1.0-video-index0 -> ../../video0
lrwxrwxrwx. 1 root root 12 28 set 03.29 pci-0000:04:00.3-usbv2-0:4:1.0-video-index1 -> ../../video1
lrwxrwxrwx. 1 root root 12 28 set 03.29 pci-0000:04:00.3-usbv2-0:4:1.2-video-index0 -> ../../video2
lrwxrwxrwx. 1 root root 12 28 set 03.29 pci-0000:04:00.3-usbv2-0:4:1.2-video-index1 -> ../../video3
```

**Give more information if you have**
IR camera (/dev/video2) flashes briefly for about half a second and then stops working showing only a black screen in the preview. This happens everytime it is llaunched. 
One time I forgot to close a camera app that was using the normal webcam, on that occasion the ir camera was warking fine and can consistently reproduce this. 
I'm new-ish to Linux so my apologies if something is missing, let me know if you need anything else :)

**Additional info**
 - Computer (or camera) model: HP Envy x360 15-fh0002nl, sometimes known as fh0000 or fh0xxx
 - Linux distribution: Ultramarine Linux 40, based on Fedora 40
 - Version of linux-enable-ir-emitter:  6.0.3

**Comment by EmixamPP** [comment]
Execute 
1. sudo linux-enable-ir-emitter -v tweak
2. input 2
3. input 1 3 2 0 0 0 0 0 0
4. look at the video feedback and the ir emitter, does it work?
5. if not retry with 1 3 3 0 0 0 0 0 0
6. does it work?
7. if not paste output here

**Comment by madesho** [comment]
```
Executing tweak command.
Checking if /dev/video0 is a grayscale camera.
Checking if /dev/video1 is a grayscale camera.
Checking if /dev/video2 is a grayscale camera.
/dev/video2 is a grayscale camera.
Tweaking the camera /dev/video2
Caution, you could break the camera.
Previous configuration found.
0) unit: 14, selector: 6, control: 1 3 1 0 0 0 0 0 0
1) unit: 14, selector: 9, control: 1 0 0 0
2) exit
Choose an instruction to tweak: 0
minimum:
maximum: 1 3 3 0 0 0 0 0 0
initial: 1 3 1 0 0 0 0 0 0
current: 1 3 1 0 0 0 0 0 0
status: enable
new current or status:  1 3 2 0 0 0 0 0 0
Invalid value for the instruction.
0) unit: 14, selector: 6, control: 1 3 1 0 0 0 0 0 0
1) unit: 14, selector: 9, control: 1 0 0 0
2) exit
Choose an instruction to tweak: terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.10.0) /home/runner/work/linux-enable-ir-emitter/linux-enable-ir-emitter/.github/workflows/deps/build/opencv/src/opencv/modules/highgui/src/window.cpp:973: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'imshow'

zsh: IOT instruction  sudo linux-enable-ir-emitter -v tweak
```

Seems that I can't change the configuration, am I doing something wrong?

**Comment by EmixamPP** [comment]
Could you retry with the new v6.0.4? I think it should work now; I fixed a bug that you reported here!

**Comment by madesho** [comment]
I tried to uninstall the old version and installed the new one and the camera was working correctly without changing any setting for some reason? Then I installed Howdy and it did the same thing that I described the other day with a few flashes and then the black preview. 
Went back to try with your solution of the other day and now it changes the settings correctly, but it still doesn't work properly. 
Also tried to uninstall Howdy and its dependencies to see if was some kind of conflict with something, but the problem is still there

**Comment by EmixamPP** [comment]
First using the tweak command assign the value `1 3 2 0 0 0 0 0 0` to the instruction 0
Then exit and:
1. execute `linux-enable-ir-emitter -d /dev/video2 test` does the emitter flash?
2. execute `linux-enable-ir-emitter -d /dev/video2 test` does the emitter flash?
3. execute `linux-enable-ir-emitter run`
4. execute `linux-enable-ir-emitter -d /dev/video2 test` does the emitter flash?
5. execute `linux-enable-ir-emitter -d /dev/video2 test` does the emitter flash?

We will determine if the applying of the instruction is permanent or not

**Comment by madesho** [comment]
Sorry for the late answer, followed your instructions and it's the same thing as always, some flashes and then black screen

**Comment by EmixamPP** [comment]
I just want to let you know that I am working on a kernel space solution (instead of user space as currently), this should solve this kind of issue (I think).

**Comment by EmixamPP** [comment]
@zkurdi45 could be something that may disable using the `tweak` command, see [readme](https://github.com/EmixamPP/linux-enable-ir-emitter?tab=readme-ov-file#how-do-i-tweak-my-camera)
